import type { Teacher } from "./schema";

// Datos de ejemplo
export const teachersData: Teacher[] = [
  {
    id: "TCH001",
    name: "Dr. Roberto Martínez",
    email: "roberto.martinez@example.com",
    status: "active",
    hireDate: "2020-08-15",
    department: "Computer Science",
    rating: 4.8,
  },
  {
    id: "TCH002",
    name: "Prof. Elena González",
    email: "elena.gonzalez@example.com",
    status: "active",
    hireDate: "2019-09-01",
    department: "Mathematics",
    rating: 4.9,
  },
  {
    id: "TCH003",
    name: "Dr. Miguel Ángel Ruiz",
    email: "miguel.ruiz@example.com",
    status: "on-leave",
    hireDate: "2018-01-10",
    department: "Physics",
    rating: 4.6,
  },
  {
    id: "TCH004",
    name: "Prof. Carmen Vega",
    email: "carmen.vega@example.com",
    status: "active",
    hireDate: "2021-09-01",
    department: "Engineering",
    rating: 4.7,
  },
  {
    id: "TCH005",
    name: "Dr. Francisco López",
    email: "francisco.lopez@example.com",
    status: "inactive",
    hireDate: "2017-03-20",
    department: "Chemistry",
    rating: 4.3,
  },
  {
    id: "TCH006",
    name: "Prof. Isabel Romero",
    email: "isabel.romero@example.com",
    status: "active",
    hireDate: "2022-01-15",
    department: "Computer Science",
    rating: 4.9,
  },
  {
    id: "TCH007",
    name: "Dr. Alberto Jiménez",
    email: "alberto.jimenez@example.com",
    status: "active",
    hireDate: "2019-09-01",
    department: "Biology",
    rating: 4.5,
  },
  {
    id: "TCH008",
    name: "Prof. Lucía Morales",
    email: "lucia.morales@example.com",
    status: "active",
    hireDate: "2020-09-01",
    department: "Engineering",
    rating: 4.8,
  },
];
