import type { Student } from "./schema";

// Datos de ejemplo
export const studentsData: Student[] = [
  {
    id: "ST001",
    name: "Ana García",
    email: "ana.garcia@example.com",
    status: "active",
    enrollmentDate: "2023-09-01",
    program: "Ingeniería en Software",
    gpa: 3.8,
  },
  {
    id: "ST002",
    name: "Carlos Rodríguez",
    email: "carlos.rodriguez@example.com",
    status: "active",
    enrollmentDate: "2023-09-01",
    program: "Ciencias de la Computación",
    gpa: 3.5,
  },
  {
    id: "ST003",
    name: "María López",
    email: "maria.lopez@example.com",
    status: "graduated",
    enrollmentDate: "2021-09-01",
    program: "Ingeniería en Sistemas",
    gpa: 3.9,
  },
  {
    id: "ST004",
    name: "Juan Martínez",
    email: "juan.martinez@example.com",
    status: "active",
    enrollmentDate: "2022-09-01",
    program: "Desarrollo Web",
    gpa: 3.2,
  },
  {
    id: "ST005",
    name: "Laura Hernández",
    email: "laura.hernandez@example.com",
    status: "inactive",
    enrollmentDate: "2023-01-15",
    program: "Ingeniería en Software",
    gpa: 2.9,
  },
  {
    id: "ST006",
    name: "Pedro Sánchez",
    email: "pedro.sanchez@example.com",
    status: "active",
    enrollmentDate: "2023-09-01",
    program: "Ciberseguridad",
    gpa: 3.7,
  },
  {
    id: "ST007",
    name: "Sofía Ramírez",
    email: "sofia.ramirez@example.com",
    status: "active",
    enrollmentDate: "2022-01-15",
    program: "Ciencia de Datos",
    gpa: 3.6,
  },
  {
    id: "ST008",
    name: "Diego Torres",
    email: "diego.torres@example.com",
    status: "graduated",
    enrollmentDate: "2020-09-01",
    program: "Ingeniería en Software",
    gpa: 3.8,
  },
];
